# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3
    hooks:
      - id: roxygenize
        additional_dependencies:
          - R6
          - checkmate (>= 2.3.2)
          - data.table (>= 1.16.0)
          - mlr3 (>= 0.20.0)
          - mlr3misc (>= 0.15.0)
          - paradox (>= 1.0.1)
      # codemeta must be above use-tidy-description when both are used
      - id: use-tidy-description
      - id: readme-rmd-rendered
      - id: parsable-R
      - id: no-browser-statement
      - id: deps-in-desc
        exclude: data-raw|inst
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=200]
      - id: file-contents-sorter
        files: '^\.Rbuildignore$'
      - id: end-of-file-fixer
        exclude: '\.Rd'
  - repo: local
    hooks:
      - id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.
ci:
  autoupdate_schedule: monthly
